---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-app
  template:
    metadata:
      labels:
        app: prod-app
    spec:
      containers:
      - name: go-webserver
        image: docker.io/carlosblinf/go-app:v1
        ports:
        - containerPort: 8080
